import type { ExtractionResult } from "./schema";

export const SYNTHETIC_ROUTER_PDF_FILENAME =
  "synthetic-router-pro-forma-invoice.pdf";
export const SYNTHETIC_ROUTER_PDF_SHA256 =
  "31b92e2ff232113b1beef3d9d52aa31abb32cb89d3d1155d5e54de5b470372be";

export const RECORDED_ROUTER_EXTRACTION = {
  schemaVersion: "1.0",
  extractionMode: "recorded_fixture",
  document: {
    kind: "pro_forma_invoice",
    fileName: SYNTHETIC_ROUTER_PDF_FILENAME,
    pageCount: 1,
    syntheticScopeId: "bwmi-router-pro-forma-v1",
  },
  facts: [
    {
      id: "documentNumber",
      field: "documentNumber",
      label: "Document number",
      rawValue: "BWMI-PI-ROUTER-001",
      value: "BWMI-PI-ROUTER-001",
      confidence: 1,
      provenance: { source: "visible_document_text", page: 1, locator: "Document number row" },
    },
    {
      id: "exporterIdentity",
      field: "exporterIdentity",
      label: "Exporter",
      rawValue: "Reviewed fixture exporter",
      value: "Reviewed fixture exporter",
      confidence: 1,
      provenance: { source: "visible_document_text", page: 1, locator: "Exporter row" },
    },
    {
      id: "producerIdentity",
      field: "producerIdentity",
      label: "Producer",
      rawValue: "Reviewed fixture producer",
      value: "Reviewed fixture producer",
      confidence: 1,
      provenance: { source: "visible_document_text", page: 1, locator: "Producer row" },
    },
    {
      id: "manufacturerIdentity",
      field: "manufacturerIdentity",
      label: "Manufacturer",
      rawValue: "Reviewed fixture manufacturer",
      value: "Reviewed fixture manufacturer",
      confidence: 1,
      provenance: { source: "visible_document_text", page: 1, locator: "Manufacturer row" },
    },
    {
      id: "importerIdentity",
      field: "importerIdentity",
      label: "Importer",
      rawValue: "Reviewed fixture importer India Pvt Ltd",
      value: "Reviewed fixture importer India Pvt Ltd",
      confidence: 1,
      provenance: { source: "visible_document_text", page: 1, locator: "Importer row" },
    },
    {
      id: "productDescription",
      field: "productDescription",
      label: "Product description",
      rawValue: "New retail integrated 2.4/5 GHz MIMO Wi-Fi router",
      value: "New retail integrated 2.4/5 GHz MIMO Wi-Fi router",
      confidence: 0.99,
      provenance: { source: "visible_document_text", page: 1, locator: "Product row" },
    },
    {
      id: "modelIdentity",
      field: "modelIdentity",
      label: "Exact model",
      rawValue: "BWMI-MIMO-245-R1",
      value: "BWMI-MIMO-245-R1",
      confidence: 1,
      provenance: { source: "visible_document_text", page: 1, locator: "Router model row" },
    },
    {
      id: "adapterModelIdentity",
      field: "adapterModelIdentity",
      label: "Adapter model",
      rawValue: "BWMI-ADAPTER-12V-R1",
      value: "BWMI-ADAPTER-12V-R1",
      confidence: 1,
      provenance: { source: "visible_document_text", page: 1, locator: "Adapter model row" },
    },
    {
      id: "originCountryCode",
      field: "originCountryCode",
      label: "Country of origin",
      rawValue: "Vietnam (VN)",
      value: "VN",
      confidence: 1,
      provenance: { source: "visible_document_text", page: 1, locator: "Country of origin row" },
    },
    {
      id: "quantity",
      field: "quantity",
      label: "Quantity",
      rawValue: "1 retail set",
      value: "1 retail set",
      confidence: 1,
      provenance: { source: "visible_document_text", page: 1, locator: "Quantity row" },
    },
    {
      id: "itemValueInr",
      field: "itemValueInr",
      label: "Item value",
      rawValue: "INR 99,999.98",
      value: "99999.98",
      confidence: 1,
      provenance: { source: "visible_document_text", page: 1, locator: "Item value row" },
    },
    {
      id: "freightInr",
      field: "freightInr",
      label: "Freight",
      rawValue: "INR 0.01",
      value: "0.01",
      confidence: 1,
      provenance: { source: "visible_document_text", page: 1, locator: "Freight row" },
    },
    {
      id: "insuranceInr",
      field: "insuranceInr",
      label: "Insurance",
      rawValue: "INR 0.01",
      value: "0.01",
      confidence: 1,
      provenance: { source: "visible_document_text", page: 1, locator: "Insurance row" },
    },
  ],
  materialQuestions: [
    {
      id: "confirmProductScope",
      question: "Does this exact shipment match every checked product-scope fact and exclusion?",
      impact: "applicability",
      relatedFields: ["productDescription", "modelIdentity", "adapterModelIdentity"],
    },
    {
      id: "confirmExternalEvidence",
      question: "What evidence and dated trade-remedy checks exist outside this invoice?",
      impact: "evidence",
      relatedFields: ["originCountryCode", "producerIdentity", "exporterIdentity"],
    },
  ],
  limitations: [
    "Verified only for this one synthetic router pro-forma invoice PDF.",
    "Visible commercial facts are extracted; legal applicability, outcomes, evidence status, and arithmetic remain outside the agent.",
  ],
} satisfies ExtractionResult;
